-- PostgreSQL Script for TicketHub Ticket Application Database

-- The tables are created in an order that respects foreign key dependencies.
-- Tables without dependencies (artists, events) are created first.

-- =================================================================
-- Table: ARTISTS
-- Stores information about musical artists or performers.
-- =================================================================
CREATE TABLE artists (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    genre VARCHAR(100),
    members TEXT,
    socials JSONB
);

-- =================================================================
-- Table: EVENTS
-- Stores details about each event.
-- =================================================================
CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    flyer VARCHAR(255) NOT NULL,
    genre VARCHAR(100) NOT NULL,
    subtitle VARCHAR(255),
    description TEXT,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    max_attendees INTEGER NOT NULL,
    avaliable_places INTEGER NOT NULL,
    status SMALLINT NOT NULL -- (0) Canceled, (1) Avaliable, (2) Ended, (3) Sold out
);

-- =================================================================
-- Table: CLIENTS
-- =================================================================
CREATE TABLE clients (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    registration_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    gender VARCHAR(50),
    birth_date DATE NOT NULL,
    phone VARCHAR(10)
);

-- =================================================================
-- Table: ORGANIZERS
-- =================================================================
CREATE TABLE organizers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    registration_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name VARCHAR(255) NOT NULL,
    socials JSONB
);

-- =================================================================
-- Table: ORDERS
-- =================================================================
CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount DECIMAL(10, 2) NOT NULL,
    payment_status SMALLINT NOT NULL, -- (0) Pending, (1) Paid, (2) Reimbursed
    client_id INTEGER NOT NULL,
    FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE RESTRICT
);

-- =================================================================
-- Table: TICKETS
-- =================================================================
CREATE TABLE tickets (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status SMALLINT NOT NULL, -- (0) Used, (1) Active, (2) Canceled, (3) Expired
    purchase_price DECIMAL(10, 2) NOT NULL,
    attendees INTEGER NOT NULL DEFAULT 1,
    remaining_attendees INTEGER NOT NULL,
    order_id INTEGER NOT NULL UNIQUE,
    event_id INTEGER NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE RESTRICT
);

-- =================================================================
-- Junction Tables
-- =================================================================

CREATE TABLE event_organizer (
    event_id INTEGER NOT NULL,
    organizer_id INTEGER NOT NULL,
    PRIMARY KEY (event_id, organizer_id),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (organizer_id) REFERENCES organizers(id) ON DELETE CASCADE
);

CREATE TABLE event_artist (
    event_id INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    PRIMARY KEY (event_id, artist_id),
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    FOREIGN KEY (artist_id) REFERENCES artists(id) ON DELETE CASCADE
);

-- =================================================================
-- Views
-- =================================================================

CREATE VIEW v_all_users AS
SELECT
    id, email, username, password, registration_date,
    'client' AS account_type
FROM clients
UNION ALL
SELECT
    id, email, username, password, registration_date,
    'organizer' AS account_type
FROM organizers;

CREATE VIEW tickets_per_client AS
SELECT t.id,
    t.status,
    t.purchase_price,
    t.attendees,
    o.order_date,
    o.total_amount,
    o.payment_status,
    o.client_id,
    c.email,
    c.username
FROM tickets t
    JOIN orders o ON o.id = t.order_id
    JOIN clients c ON c.id = o.client_id
ORDER BY c.id, o.order_date;

-- =================================================================
-- Triggers
-- =================================================================

CREATE OR REPLACE FUNCTION set_current_registration_date()
RETURNS TRIGGER AS $$
BEGIN
    NEW.registration_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_clients_registration_date
BEFORE INSERT ON clients
FOR EACH ROW
EXECUTE FUNCTION set_current_registration_date();

CREATE TRIGGER trg_organizers_registration_date
BEFORE INSERT ON organizers
FOR EACH ROW
EXECUTE FUNCTION set_current_registration_date();

-- =================================================================
-- Mock Data
-- =================================================================

INSERT INTO artists (name, description, genre, members, socials) VALUES
('The Crimson Hex', 'A high-energy rock band known for their powerful riffs.', 'Rock', 'Alex (Vocals), Maria (Guitar), Sam (Bass), Leo (Drums)', '{"spotify": "spotify.com/crimsonhex", "instagram": "instagram.com/crimsonhex"}'),
('Static Rebellion', 'An indie band with a unique blend of folk and electronic sounds.', 'Indie', 'Chloe (Vocals/Synth), Ben (Guitar)', '{"spotify": "spotify.com/staticrebellion"}'),
('Voltage Valley', 'A classic metal band that delivers thunderous anthems.', 'Metal', 'Vince (Vocals), Jax (Guitar), Spike (Bass), Roxy (Drums)', '{"spotify": "spotify.com/voltagevalley", "instagram": "instagram.com/voltagevalley"}'),
('Luna Sol', 'A rising latin pop star with catchy rhythms.', 'Pop', 'Luna (Vocals)', '{"instagram": "ig.com/lunasol"}'),
('Los Viajeros', 'Romantic ballads for the modern age.', 'Latin Pop', 'Carlos, Miguel, Jose', '{"spotify": "sp.com/viajeros"}'),
('Sofia Dreams', 'Acoustic pop covers and originals.', 'Acoustic', 'Sofia (Guitar/Vocals)', '{"youtube": "yt.com/sofiadreams"}'),
('Ritmo Urbano', 'High energy reggaeton duo.', 'Reggaeton', 'Dany Y, MC Z', '{"tiktok": "tk.com/ritmourbano"}'),
('Banda El Recuerdo', 'Traditional sinaloense banda music.', 'Banda', '15 member ensemble', '{"facebook": "fb.com/bandarecuerdo"}'),
('The Rusty Gears', 'Grunge revivalists from the north.', 'Grunge', 'Tom, Jerry, Mike', '{"bandcamp": "bc.com/rustygears"}'),
('Neon Horizon', 'Synth-wave meets alternative rock.', 'Synth-Rock', 'Sarah (Keys), Dan (Drums)', '{"spotify": "sp.com/neonhorizon"}'),
('Echoes of Mars', 'Space rock with psychedelic visuals.', 'Psychedelic', 'Unknown', '{"instagram": "ig.com/echoes"}'),
('Blackout City', 'Hard rock with a punk attitude.', 'Hard Rock', 'Viper, Rex, Slash', '{"website": "blackout.com"}'),
('Silent Screams', 'Emo-core veterans returning to stage.', 'Emo', 'Jared, Pete, Wentz', '{"twitter": "x.com/silentscreams"}'),
('Jazz Cats Trio', 'Smooth jazz for evening vibes.', 'Jazz', 'Leo (Sax), Ray (Piano)', '{"website": "jazzcats.com"}'),
('Blue Moon Quartet', 'Classic blues standards.', 'Blues', 'Big Mike & The Boys', '{"spotify": "sp.com/bluemoon"}'),
('Sinaloa Symphony', 'Chamber orchestra group.', 'Classical', 'Various', '{"website": "sinaloasymphony.org"}'),
('Sax in the City', 'Solo saxophone performances.', 'Jazz', 'Kenny G (Tribute)', '{"youtube": "yt.com/saxcity"}'),
('DJ K-OS', 'Dubstep and drum & bass producer.', 'Electronic', 'Kevin O.', '{"soundcloud": "sc.com/djk-os"}'),
('Techno Bunker', 'Deep house and minimal techno.', 'Techno', 'Hans, Franz', '{"ra": "ra.co/technobunker"}'),
('Vaporwave Dreams', 'Nostalgic 80s beats.', 'Lo-Fi', 'SadBoy99', '{"bandcamp": "bc.com/vapor"}'),
('Electric Youth', 'Upbeat EDM for festivals.', 'EDM', 'Alice, Bob', '{"instagram": "ig.com/electricyouth"}'),
('Norteño Kings', 'Classic accordion powered norteño.', 'Norteño', 'Los Reyes', '{"facebook": "fb.com/nortenokings"}'),
('Mariachi Oro', 'Golden standard mariachi band.', 'Mariachi', '10 members', '{"website": "mariachioro.com"}'),
('Sierreño Brothers', 'Guitar based regional music.', 'Sierreño', 'Juan, Pedro', '{"tiktok": "tk.com/sierrenobros"}'),
('Folklorico Vivo', 'Traditional dance and music accompaniment.', 'Folk', 'Dance Troupe', '{"culture": "cultura.gob.mx"}'),
('Paper Airplanes', 'Soft indie rock with poetic lyrics.', 'Indie', 'Martha, Stewart', '{"spotify": "sp.com/paperairplanes"}'),
('The Hipsters', 'Irony and banjos.', 'Indie Folk', 'Guy with beard', '{"instagram": "ig.com/thehipsters"}'),
('Garage Days', 'Raw garage rock sound.', 'Garage Rock', 'Teens from the block', '{"bandcamp": "bc.com/garagedays"}'),
('Dream Pop Collective', 'Ethereal vocals and heavy reverb.', 'Dream Pop', 'Liz, Cocteau', '{"youtube": "yt.com/dreampop"}'),
('Iron Fist', 'Heavy metal thunder.', 'Metal', 'Bruce, Steve', '{"website": "ironfist.com"}'),
('Doom Gloom', 'Slow, heavy, and atmospheric.', 'Doom Metal', 'Ozzy (Tribute)', '{"spotify": "sp.com/doomgloom"}'),
('Speed Demons', 'Fast riffs and double bass pedals.', 'Thrash Metal', 'James, Lars', '{"meta": "fb.com/speeddemons"}'),
('Symphonic Souls', 'Metal with operatic vocals.', 'Symphonic Metal', 'Tarja, Marco', '{"website": "symphonicsouls.com"}');

INSERT INTO events (name, flyer, genre, subtitle, description, city, address, start_time, price, max_attendees, avaliable_places, status) VALUES
('Rock Revival Tour', 'rock_poster.jpg', 'Rock', 'Classic rock anthems that never die.', 'Get ready to headbang! A lineup of legendary bands is here to play all the hits that shaped a generation.', 'Culiacán', 'Foro Tecate, Av. Federalismo', '2025-11-15 20:00:00-07', 500.00, 2000, 1500, 1),
('Indie Folk Gathering', 'indie_poster.jpg', 'Indie', 'Heartfelt lyrics and rustic charm.', 'Discover your new favorite indie folk artists in an intimate and cozy setting.', 'Culiacán', 'Teatro Lince, Blvd. Rolando Arjona', '2025-12-05 19:30:00-07', 400.00, 800, 600, 1),
('Retro Night 2025', 'electronic_poster.jpg', 'Pop', 'Back to the 80s', 'A night of nostalgia featuring the best hits of the 80s.', 'Culiacán', 'Casino de la Cultura', '2025-10-10 20:00:00-07', 300.00, 500, 0, 2),
('Halloween Metal Bash', 'metal_poster.jpg', 'Metal', 'Spooky heavy riffs', 'The loudest costume party in the city.', 'Culiacán', 'Underground Club', '2025-10-31 21:00:00-07', 450.00, 300, 0, 2),
('Winter Jazz Gala', 'jazz_poster.jpg', 'Jazz', 'Smooth sounds for cold nights', 'An elegant evening with the best jazz trios.', 'Culiacán', 'Teatro MIA', '2025-12-15 19:00:00-07', 800.00, 400, 350, 1),
('Gran Baile de Año Nuevo', 'acoustic_poster.jpg', 'Banda', 'Welcome 2026', 'Celebrate the new year with Banda El Recuerdo.', 'Culiacán', 'Salón 53', '2025-12-31 22:00:00-07', 1500.00, 1000, 800, 1),
('Indie Fest Vol. 4', 'indie_poster.jpg', 'Indie', 'Local talent showcase', 'Support local bands in this all-day festival.', 'Culiacán', 'Parque Las Riberas', '2026-01-15 14:00:00-07', 200.00, 5000, 4500, 1),
('Techno Warehouse', 'electronic_poster.jpg', 'Techno', 'Rave until dawn', 'Underground electronic music experience.', 'Culiacán', 'Secret Location', '2026-01-20 23:00:00-07', 350.00, 200, 50, 1),
('Norteño vs Sierreño', 'acoustic_poster.jpg', 'Regional', 'The ultimate duel', 'Two styles, one stage.', 'Culiacán', 'Palenque', '2026-02-05 20:00:00-07', 600.00, 3000, 2500, 1),
('Valentine Acoustic', 'acoustic_poster.jpg', 'Acoustic', 'Love is in the air', 'Romantic dinner and show.', 'Culiacán', 'Jardín Botánico', '2026-02-14 19:00:00-07', 1200.00, 100, 20, 1),
('Rock in the Park', 'rock_poster.jpg', 'Rock', 'Open air concert', 'Bring your blanket and enjoy the show.', 'Culiacán', 'Isla de Orabá', '2026-03-01 17:00:00-07', 0.00, 10000, 10000, 1),
('Symphony of Spring', 'acoustic_poster.jpg', 'Classical', 'Vivaldi and more', 'The Sinaloa Symphony welcomes spring.', 'Culiacán', 'Teatro Pablo de Villavicencio', '2026-03-21 18:00:00-07', 500.00, 1000, 800, 1),
('Reggaeton Beach Party', 'reggaeton_poster.jpg', 'Reggaeton', 'Sun, sand, and beats', 'Transportation included to Altata.', 'Navolato', 'Altata Beach Club', '2026-04-05 12:00:00-07', 700.00, 1500, 1000, 1),
('Metal Mayhem', 'metal_poster.jpg', 'Metal', 'Moshpit guaranteed', 'Five bands, one night of destruction.', 'Culiacán', 'Estadio Universitario', '2026-04-20 18:00:00-07', 400.00, 5000, 4000, 1),
('Synthwave Sunset', 'electronic_poster.jpg', 'Synth-Rock', 'Neon lights and vibes', 'A visual and auditory experience.', 'Culiacán', 'Roof Top Bar', '2026-05-10 19:00:00-07', 300.00, 150, 100, 1),
('Blues & BBQ', 'jazz_poster.jpg', 'Blues', 'Good food, sad songs', 'All you can eat BBQ with live blues.', 'Culiacán', 'Ranch House', '2026-05-25 13:00:00-07', 900.00, 200, 150, 1),
('Pop Icons Tribute', 'indie_poster.jpg', 'Pop', 'Sing along', 'Tribute bands playing top 40 hits.', 'Culiacán', 'La 20', '2026-06-05 21:00:00-07', 250.00, 300, 200, 1),
('Electronic Forest', 'electronic_poster.jpg', 'EDM', 'Dance in nature', 'Camping and music festival.', 'Imala', 'Imala Resort', '2026-06-20 10:00:00-07', 1800.00, 2000, 1800, 1),
('Mariachi Gala', 'acoustic_poster.jpg', 'Mariachi', 'Mexican Pride', 'A celebration of our traditions.', 'Culiacán', 'Plazuela Rosales', '2026-07-01 18:00:00-07', 0.00, 5000, 5000, 1),
('Grunge Garage', 'rock_poster.jpg', 'Grunge', 'Flannel shirts welcome', 'Raw energy and loud amps.', 'Culiacán', 'Backyard Venue', '2026-07-15 20:00:00-07', 150.00, 100, 20, 1),
('Summer Vibes', 'indie_poster.jpg', 'Pop', 'Pool party', 'DJ sets and live pop acts.', 'Culiacán', 'Hotel Lucerna Pool', '2026-07-30 14:00:00-07', 600.00, 300, 250, 1),
('The Grand Finale', 'rock_poster.jpg', 'Rock', 'End of season', 'A massive concert to end the season.', 'Culiacán', 'Estadio Tomateros', '2026-08-15 20:00:00-07', 2000.00, 15000, 12000, 1);

INSERT INTO organizers (email, username, password, name, socials) VALUES
('promo.events@email.com', 'promomusic', 'hashed_password_3', 'PromoMusic Culiacán', '{"website": "promomusic.com"}'),
('fest.master@email.com', 'festmaster', 'hashed_pass_4', 'FestMaster Global', '{"website": "festmaster.com", "facebook": "fb.com/festmaster"}'),
('culiacan.arts@email.com', 'clnarts', 'hashed_pass_5', 'Culiacán Arts Council', '{"instagram": "ig.com/clnarts"}'),
('indie.vibes@email.com', 'indievibes', 'hashed_pass_6', 'Indie Vibes Promotions', '{"twitter": "x.com/indievibes"}'),
('mega.shows@email.com', 'megashows', 'hashed_pass_7', 'Mega Shows MX', '{"website": "megashows.mx"}'),
('underground.beat@email.com', 'underbeat', 'hashed_pass_8', 'The Underground Beat', '{"tiktok": "tiktok.com/@underbeat"}');

INSERT INTO event_organizer (event_id, organizer_id) VALUES
(1, 1), (2, 1),
(3, 2), (4, 6), (5, 3), (6, 5), (7, 4), (8, 6), (9, 5),
(10, 3), (11, 2), (12, 3), (13, 2), (14, 6),
(15, 4), (16, 5), (17, 2), (18, 6), (19, 3),
(20, 6), (21, 2), (22, 5);

INSERT INTO event_artist (event_id, artist_id) VALUES
(1, 1), (1, 3), (2, 2),
(3, 4), (3, 6),
(4, 30), (4, 31),
(5, 14), (5, 17),
(6, 8),
(7, 26), (7, 27), (7, 28),
(8, 19), (8, 21),
(9, 22), (9, 24),
(10, 5), (10, 6),
(11, 9), (11, 12),
(12, 16),
(13, 7), (13, 4),
(14, 32), (14, 33), (14, 12),
(15, 10), (15, 20),
(16, 15),
(17, 6),
(18, 18), (18, 21), (18, 19),
(19, 23),
(20, 9), (20, 28),
(21, 4), (21, 7),
(22, 12), (22, 30), (22, 1);

UPDATE events
SET avaliable_places = 0, status = 3
WHERE id IN (7, 8);
